#define SYSTEM_PROCESS_REAL_TIME_PRIORITY '0'
#define SYSTEM_MEMORY_TOTAL 1048576 // 1048576 bytes = 1024 mega bytes
#define SYSTEM_STATUS_NORMAL 0
#define SYSTEM_STATUS_TURNING_OFF 1
#define SYSTEM_STATUS_FINISHED 2
#define SYSTEM_STATUS_TURNED_OFF 3
#define SYSTEM_STATUS_ERROR 4

#define CPUS_TOTAL 4
#define PRINTERS_TOTAL 2
#define SCANNERS_TOTAL 1
#define MODEMS_TOTAL 1
#define CD_DRIVERS_TOTAL 2
